name: nightly
on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY_IMAGE: user/app

jobs:
  docker:
    name: 'Nightly Build'
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
    - uses: 'actions/checkout@v2'
    - uses: extractions/setup-just@v1

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: clux
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Prepare
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build nightly image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ matrix.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
        push: false
        build-args: |
          CHANNEL=nightly
        tags: clux/muslrust:temp

    - name: Compute tags
      shell: bash
      run: |
        docker run clux/muslrust:temp rustc --version
        RUST_VER="$(docker run clux/muslrust:temp rustc --version | grep -oE "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]")"
        RUST_DATE="$(date +"%Y-%m-%d")"
        RUST_CHANNEL=nightly
        echo "TAG1=clux/muslrust:${RUST_CHANNEL}" >> $GITHUB_ENV
        echo "TAG2=clux/muslrust:${RUST_CHANNEL}-${RUST_DATE}" >> $GITHUB_ENV
        echo "TAG3=clux/muslrust:${RUST_VER}-${RUST_CHANNEL}-${RUST_DATE}" >> $GITHUB_ENV

    - name: Run tests
      shell: bash
      run: just test

    - name: Push image under computed tags
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: |
          CHANNEL=nightly
        push: ${{ github.event_name != 'pull_request' }}
        tags: clux/muslrust:latest,${{ env.TAG1 }},${{ env.TAG2 }},${{ env.TAG3 }}
